version: '3'
services:
  db:
    image: nemanjaa21/drs-projekat:mysqldrs
    restart: always
    ports:
      - "9000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test_db
    volumes:
      - ./database/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql

  bankui:
     build: ./bankUI/
     depends_on:
       - db
     ports: 
       - "15001:15001"
     links: 
       - db
     volumes:
       - ./bankUI/:/usr/src/app

  engine:
     build: ./engine/
     depends_on:
       - db
     ports:
       - "15002:15002"
     links: 
       - db
     volumes:
       - ./engine/:/usr/src/app

volumes:
  db:
    driver: local
  bankui:
    driver: local
  engine:
    driver: local

networks:
  default:
    driver: bridge